[tool.poetry]
name = "insta-clone-backend"
version = "0.1.0"
description = ""
authors = ["Darveloper <darveloper@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.9"
Pillow = "^7.2.0"
bootstrap4 = "^0.1.0"
flake8 = "^3.8.3"
django-environ = "^0.4.5"
gunicorn = "^20.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
